"use client";
import {useEffect,useMemo,useState} from "react";
import {RefreshCw} from "lucide-react";
import {Badge,Button,Card,PageHeader} from "@/components/ui";
import {Manager,Payment,useAdminStore} from "@/components/store";
import {DateRangePicker} from "@/components/date-range-picker";
import {inRange,isEformSignedStatus,won} from "@/lib/utils";
import {effectivePayments,isContractPayment,paymentRemaining,paymentRootId} from "@/lib/payment-metrics";

const activeManagers:Manager[]=["신홍규","이중호"];
function today(){return new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function isoDate(v:string){if(!v)return "";const d=new Date(v);if(Number.isNaN(d.getTime()))return v.slice(0,10);return new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function monthBounds(month:string){const [y,m]=month.split("-").map(Number);return{start:`${month}-01`,end:`${month}-${String(new Date(y,m,0).getDate()).padStart(2,"0")}`}}
function currentMonth(){return today().slice(0,7)}
function shiftMonth(month:string,delta:number){const [y,m]=month.split("-").map(Number);const d=new Date(y,m-1+delta,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function pct(n:number,d:number){return d>0?`${((n/d)*100).toFixed(1)}%`:"0.0%"}
function paidTotal(payments:Payment[],customerId?:string){return payments.filter(p=>(!customerId||p.customerId===customerId)&&p.status!=="환불"&&isContractPayment(p)).reduce((a,b)=>a+(b.paidAmount||0),0)}
function realPaidTotal(payments:Payment[],customerId?:string){return payments.filter(p=>(!customerId||p.customerId===customerId)&&p.status!=="환불").reduce((a,b)=>a+(b.paidAmount||0),0)}
function isLateIncident(p:Payment,now=today()){if(!p.dueDate||p.status==="환불")return false;if(p.status==="연체"||p.status==="미납")return true;if(p.paidDate&&p.paidDate>p.dueDate)return true;return p.dueDate<now&&p.status!=="완료"}
function isOnTimePaid(p:Payment){return p.status==="완료"&&!!p.dueDate&&!!p.paidDate&&p.paidDate<=p.dueDate&&(p.paidAmount||0)>=(p.dueAmount||0)}
function dayOffset(base:string,days:number){const [y,m,d]=base.split("-").map(Number);const x=new Date(y,m-1,d+days);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`}
function Stat({label,value,sub,tone="normal"}:{label:string;value:string|number;sub?:string;tone?:"normal"|"red"|"blue"|"green"}){return <Card className="p-4"><div className="text-xs font-semibold text-slate-500">{label}</div><div className={`mt-2 text-xl font-bold ${tone==="red"?"text-red-600":tone==="blue"?"text-blue-700":tone==="green"?"text-emerald-700":"text-slate-900"}`}>{value}</div>{sub&&<div className="mt-1 text-[11px] leading-4 text-slate-400">{sub}</div>}</Card>}

export function Analytics(){
 const s=useAdminStore();const m=monthBounds(currentMonth());const [start,setStart]=useState(m.start);const [end,setEnd]=useState(m.end);const [refreshing,setRefreshing]=useState(false);
 useEffect(()=>{const id=window.setInterval(()=>{void s.refresh()},15000);return()=>window.clearInterval(id)},[s.refresh]);
 async function refresh(){setRefreshing(true);try{await s.refresh()}finally{setRefreshing(false)}}
 function resetMonth(){const x=monthBounds(currentMonth());setStart(x.start);setEnd(x.end)}
 function setAll(){const dates=[...s.customers.map(x=>x.createdAt),...s.metaLeads.map(x=>isoDate(x.createdAt)),...s.payments.map(x=>x.dueDate),...s.repayments.map(x=>x.dueDate),...s.additionalContracts.map(x=>x.contractDate||isoDate(x.createdTime||"")),...s.recoveries.map(x=>x.recoveryDate||isoDate(x.createdTime||""))].filter(Boolean).sort();setStart(dates[0]||today());setEnd(today())}
 const metrics=useMemo(()=>{
  const now=today();const maturedEnd=end<now?end:now;const signedCustomers=s.customers.filter(c=>isEformSignedStatus(c.eformsignStatus));const signedIds=new Set(signedCustomers.map(c=>c.id));const operationalSignedIds=new Set(signedCustomers.filter(c=>!c.isAccident).map(c=>c.id));
  const periodLeads=s.metaLeads.filter(x=>inRange(isoDate(x.createdAt),start,end));
  const periodCustomers=s.customers.filter(x=>inRange(x.createdAt,start,end));
  const baseContractEvents=signedCustomers.filter(x=>(x.isAccident?x.contractAmount:(x.baseContractAmount??x.contractAmount))>0&&inRange(x.contractDate||x.createdAt,start,end)).map(x=>({customerId:x.id,date:x.contractDate||x.createdAt,amount:x.isAccident?x.contractAmount:(x.baseContractAmount??x.contractAmount)}));
  const additionalContractEvents=s.additionalContracts.filter(x=>operationalSignedIds.has(x.customerId)&&x.contractAmount>0&&inRange(x.contractDate||isoDate(x.createdTime||""),start,end)).map(x=>({customerId:x.customerId,date:x.contractDate||isoDate(x.createdTime||""),amount:x.contractAmount}));
  const periodContracts=[...baseContractEvents,...additionalContractEvents];
  const periodPaid=s.payments.filter(p=>signedIds.has(p.customerId)&&p.status!=="환불"&&p.paidDate&&inRange(p.paidDate,start,end));
  const contractSales=periodContracts.reduce((a,b)=>a+b.amount,0);const realSales=periodPaid.reduce((a,b)=>a+b.paidAmount,0);
  const signedPayments=s.payments.filter(p=>signedIds.has(p.customerId));const allContract=signedCustomers.reduce((a,b)=>a+b.contractAmount,0);const allPaid=realPaidTotal(signedPayments);const allContractPaid=paidTotal(signedPayments);const receivable=s.customers.filter(c=>c.contractAmount>0).reduce((sum,c)=>sum+Math.max(0,c.contractAmount-paidTotal(s.payments,c.id)),0);
  const convertedLeads=periodLeads.filter(l=>l.status==="고객등록완료"||!!l.customerId);const contractedLeads=periodLeads.filter(l=>{const c=l.customerId?s.customers.find(x=>x.id===l.customerId):undefined;return !!c&&isEformSignedStatus(c.eformsignStatus)&&c.contractAmount>0});
  const matured=s.payments.filter(p=>operationalSignedIds.has(p.customerId)&&p.status!=="환불"&&isContractPayment(p)&&p.dueDate&&inRange(p.dueDate,start,maturedEnd));const late=matured.filter(p=>isLateIncident(p,now));const onTime=matured.filter(isOnTimePaid);
  const active=effectivePayments(s.payments).filter(p=>operationalSignedIds.has(p.customerId)&&p.status!=="환불"&&isContractPayment(p));const currentOverdue=active.filter(p=>isLateIncident(p,now)&&p.status!=="완료");const overdueAmount=currentOverdue.reduce((a,b)=>a+paymentRemaining(b),0);const overdueCustomers=new Set(currentOverdue.map(p=>p.customerId)).size;
  const periodReschedules=s.payments.filter(p=>operationalSignedIds.has(p.customerId)&&p.scheduleType==="재약정"&&inRange(isoDate(p.createdTime||""),start,end));const maturedReschedules=s.payments.filter(p=>operationalSignedIds.has(p.customerId)&&p.scheduleType==="재약정"&&p.dueDate&&p.dueDate<=now);const successfulReschedules=maturedReschedules.filter(p=>p.status==="완료");
  const groups=new Map<string,Payment[]>();for(const p of s.payments.filter(p=>operationalSignedIds.has(p.customerId))){const k=paymentRootId(p);groups.set(k,[...(groups.get(k)||[]),p])}const repeatCustomers=new Set<string>();for(const group of groups.values()){if(group.filter(p=>isLateIncident(p,now)).length>=2)repeatCustomers.add(group[0]?.customerId)}
  const next7=dayOffset(now,7),next30=dayOffset(now,30);const upcoming7=active.filter(p=>p.status!=="완료"&&p.dueDate>=now&&p.dueDate<=next7).reduce((a,b)=>a+paymentRemaining(b),0);const upcoming30=active.filter(p=>p.status!=="완료"&&p.dueDate>=now&&p.dueDate<=next30).reduce((a,b)=>a+paymentRemaining(b),0);
  const periodRepayments=s.repayments.filter(r=>operationalSignedIds.has(r.customerId)&&r.dueDate&&inRange(r.dueDate,start,end));const maturedRepayments=periodRepayments.filter(r=>r.dueDate<=now);const completedRepayments=maturedRepayments.filter(r=>r.status==="상환완료"||r.status==="종결");
  const periodLenders=s.lenders.filter(l=>inRange(l.createdAt,start,end));const periodRecoveries=s.recoveries.filter(r=>signedIds.has(r.customerId)&&inRange(r.recoveryDate||isoDate(r.createdTime||""),start,end));const recoverySales=periodRecoveries.reduce((a,b)=>a+b.amount,0);
  return{periodLeads,periodCustomers,periodContracts,periodPaid,contractSales,realSales,allContract,allPaid,allContractPaid,receivable,convertedLeads,contractedLeads,matured,late,onTime,currentOverdue,overdueAmount,overdueCustomers,periodReschedules,maturedReschedules,successfulReschedules,repeatCustomers,upcoming7,upcoming30,periodRepayments,maturedRepayments,completedRepayments,periodLenders,periodRecoveries,recoverySales};
 },[s.customers,s.payments,s.repayments,s.lenders,s.metaLeads,s.additionalContracts,s.recoveries,start,end]);
 const teamManagers=useMemo(()=>Array.from(new Set<Manager>([...activeManagers,...s.customers.map(c=>c.manager).filter(Boolean)])),[s.customers]);
 const team=useMemo(()=>teamManagers.map(manager=>{const customers=s.customers.filter(c=>c.manager===manager);const periodCustomers=customers.filter(c=>inRange(c.createdAt,start,end));const signedCustomers=customers.filter(c=>isEformSignedStatus(c.eformsignStatus));const customerIds=new Set(signedCustomers.map(c=>c.id));const operationalCustomerIds=new Set(signedCustomers.filter(c=>!c.isAccident).map(c=>c.id));const baseContracts=signedCustomers.filter(c=>(c.isAccident?c.contractAmount:(c.baseContractAmount??c.contractAmount))>0&&inRange(c.contractDate||c.createdAt,start,end)).map(c=>c.isAccident?c.contractAmount:(c.baseContractAmount??c.contractAmount));const extraContracts=s.additionalContracts.filter(a=>operationalCustomerIds.has(a.customerId)&&a.contractAmount>0&&inRange(a.contractDate||isoDate(a.createdTime||""),start,end)).map(a=>a.contractAmount);const contract=[...baseContracts,...extraContracts].reduce((a,b)=>a+b,0);const contracts=baseContracts.length+extraContracts.length;const real=s.payments.filter(p=>customerIds.has(p.customerId)&&p.status!=="환불"&&p.paidDate&&inRange(p.paidDate,start,end)).reduce((a,b)=>a+b.paidAmount,0);const totalContract=signedCustomers.reduce((a,b)=>a+b.contractAmount,0);const totalPaid=s.payments.filter(p=>customerIds.has(p.customerId)&&p.status!=="환불"&&isContractPayment(p)).reduce((a,b)=>a+b.paidAmount,0);const receivable=customers.filter(c=>c.contractAmount>0).reduce((sum,c)=>sum+Math.max(0,c.contractAmount-paidTotal(s.payments,c.id)),0);const activeOverdue=new Set(effectivePayments(s.payments).filter(p=>operationalCustomerIds.has(p.customerId)&&isContractPayment(p)&&p.status!=="완료"&&isLateIncident(p)).map(p=>p.customerId)).size;return{manager,newCustomers:periodCustomers.length,contracts,contract,real,receivable,collection:pct(totalPaid,totalContract),activeOverdue}}),[teamManagers,s.customers,s.payments,s.additionalContracts,start,end]);
 const trends=useMemo(()=>Array.from({length:6},(_,i)=>shiftMonth(currentMonth(),i-5)).map(month=>{const b=monthBounds(month);const leads=s.metaLeads.filter(x=>inRange(isoDate(x.createdAt),b.start,b.end)).length;const customers=s.customers.filter(x=>inRange(x.createdAt,b.start,b.end)).length;const signedIds=new Set(s.customers.filter(c=>isEformSignedStatus(c.eformsignStatus)).map(c=>c.id));const operationalSignedIds=new Set(s.customers.filter(c=>isEformSignedStatus(c.eformsignStatus)&&!c.isAccident).map(c=>c.id));const baseContractSales=s.customers.filter(x=>isEformSignedStatus(x.eformsignStatus)&&(x.isAccident?x.contractAmount:(x.baseContractAmount??x.contractAmount))>0&&inRange(x.contractDate||x.createdAt,b.start,b.end)).reduce((a,b)=>a+(b.isAccident?b.contractAmount:(b.baseContractAmount??b.contractAmount)),0);const extraContractSales=s.additionalContracts.filter(x=>operationalSignedIds.has(x.customerId)&&x.contractAmount>0&&inRange(x.contractDate||isoDate(x.createdTime||""),b.start,b.end)).reduce((a,b)=>a+b.contractAmount,0);const contractSales=baseContractSales+extraContractSales;const realSales=s.payments.filter(p=>signedIds.has(p.customerId)&&p.status!=="환불"&&p.paidDate&&inRange(p.paidDate,b.start,b.end)).reduce((a,b)=>a+b.paidAmount,0);const overdue=s.payments.filter(p=>operationalSignedIds.has(p.customerId)&&isContractPayment(p)&&p.dueDate&&inRange(p.dueDate,b.start,b.end)&&isLateIncident(p)).length;const reschedules=s.payments.filter(p=>operationalSignedIds.has(p.customerId)&&p.scheduleType==="재약정"&&inRange(isoDate(p.createdTime||""),b.start,b.end)).length;return{month,leads,customers,contractSales,realSales,overdue,reschedules}}),[s.metaLeads,s.customers,s.payments,s.additionalContracts]);
 return <><PageHeader title="데이터 집계" description="광고·계약·수금·연체·상환 데이터를 원본 DB에서 자동 계산합니다. 계약·매출은 전자서명 완료 고객 기준이며, 미수금은 등록된 계약금액과 실제 계약대금 입금액을 기준으로 계산합니다. 화면을 열어둔 동안 15초마다 자동 갱신됩니다." action={<Button variant="secondary" disabled={refreshing} onClick={()=>void refresh()}><RefreshCw size={15} className={refreshing?"animate-spin":""}/>{refreshing?"갱신 중":"새로고침"}</Button>}/>
 <Card className="mb-4 p-4"><div className="flex flex-wrap items-end gap-3"><div><div className="mb-1.5 text-sm font-semibold">집계 기간</div><DateRangePicker start={start} end={end} onChange={(a,b)=>{setStart(a);setEnd(b)}}/></div><Button variant="secondary" onClick={resetMonth}>이번달</Button><Button variant="secondary" onClick={setAll}>전체기간</Button></div></Card>
 <div className="mb-2 text-sm font-bold text-slate-700">광고·계약 성과</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="신규 DB" value={`${metrics.periodLeads.length.toLocaleString()}건`} sub={`${start} ~ ${end}`}/><Stat label="신규 고객" value={`${metrics.periodCustomers.length.toLocaleString()}명`}/><Stat label="DB → 고객 전환율" value={pct(metrics.convertedLeads.length,metrics.periodLeads.length)} sub={`${metrics.convertedLeads.length} / ${metrics.periodLeads.length}건`} tone="blue"/><Stat label="DB → 계약 전환율" value={pct(metrics.contractedLeads.length,metrics.periodLeads.length)} sub={`${metrics.contractedLeads.length} / ${metrics.periodLeads.length}건`} tone="blue"/><Stat label="계약 건수" value={`${metrics.periodContracts.length.toLocaleString()}건`}/><Stat label="계약 매출" value={won(metrics.contractSales)} tone="blue"/><Stat label="실매출" value={won(metrics.realSales)} tone="green"/><Stat label="평균 계약금액" value={won(metrics.periodContracts.length?metrics.contractSales/metrics.periodContracts.length:0)}/></div>
 <div className="mb-2 mt-6 text-sm font-bold text-slate-700">재무·수금 현황</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="누적 계약금액" value={won(metrics.allContract)}/><Stat label="누적 실입금" value={won(metrics.allPaid)} tone="green"/><Stat label="현재 미수금" value={won(metrics.receivable)} tone="red"/><Stat label="누적 수금률" value={pct(metrics.allContractPaid,metrics.allContract)} tone="blue"/><Stat label="7일 내 받을 예정" value={won(metrics.upcoming7)} sub="현재 유효한 일정만 계산"/><Stat label="30일 내 받을 예정" value={won(metrics.upcoming30)} sub="재약정 중복 제외"/><Stat label="기간 환수 건수" value={`${metrics.periodRecoveries.length.toLocaleString()}건`} sub="계약 미수금과 별도 집계"/><Stat label="기간 환수금액" value={won(metrics.recoverySales)} tone="green"/></div>
 <div className="mb-2 mt-6 text-sm font-bold text-slate-700">분납·연체 품질</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="분납 정상 납부율" value={pct(metrics.onTime.length,metrics.matured.length)} sub={`기간 내 만기 ${metrics.matured.length}건 기준`} tone="green"/><Stat label="연체율" value={pct(metrics.late.length,metrics.matured.length)} sub="연체/미납 또는 기한 후 납부 포함" tone="red"/><Stat label="현재 연체 고객" value={`${metrics.overdueCustomers.toLocaleString()}명`} tone="red"/><Stat label="현재 연체금액" value={won(metrics.overdueAmount)} sub="재약정된 이전 일정은 중복 제외" tone="red"/><Stat label="기간 재약정 등록" value={`${metrics.periodReschedules.length.toLocaleString()}건`}/><Stat label="재약정 성공률" value={pct(metrics.successfulReschedules.length,metrics.maturedReschedules.length)} sub={`만기 도래 재약정 ${metrics.maturedReschedules.length}건 기준`} tone="blue"/><Stat label="반복 연체 고객" value={`${metrics.repeatCustomers.size.toLocaleString()}명`} sub="동일 납부건에서 2회 이상 연체" tone="red"/></div>
 <div className="mb-2 mt-6 text-sm font-bold text-slate-700">상환·업체 운영</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="기간 상환 일정" value={`${metrics.periodRepayments.length.toLocaleString()}건`}/><Stat label="상환완료율" value={pct(metrics.completedRepayments.length,metrics.maturedRepayments.length)} sub={`만기 도래 ${metrics.maturedRepayments.length}건 기준`} tone="green"/><Stat label="기간 상환 예정금액" value={won(metrics.periodRepayments.reduce((a,b)=>a+b.amount,0))}/><Stat label="기간 신규 사채업체" value={`${metrics.periodLenders.length.toLocaleString()}개`}/></div>
 <Card className="mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><div className="font-bold">영업 담당자별 성과</div><div className="mt-1 text-xs text-slate-500">영업 담당자 기준 선택 기간 성과 + 현재 미수/연체 스냅샷</div></div><div className="overflow-x-auto"><table className="admin-responsive-table w-full min-w-[980px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{["영업 담당자","신규고객","계약건수","계약매출","실매출","현재 미수금","누적 수금률","현재 연체고객"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{team.map(x=><tr key={x.manager} className="border-t border-slate-100"><td className="px-4 py-3 font-bold">{x.manager}</td><td className="px-4 py-3">{x.newCustomers}명</td><td className="px-4 py-3">{x.contracts}건</td><td className="px-4 py-3">{won(x.contract)}</td><td className="px-4 py-3 font-semibold text-blue-700">{won(x.real)}</td><td className="px-4 py-3 font-semibold text-red-600">{won(x.receivable)}</td><td className="px-4 py-3">{x.collection}</td><td className="px-4 py-3">{x.activeOverdue?<Badge tone="red">{x.activeOverdue}명</Badge>:<Badge tone="green">0명</Badge>}</td></tr>)}</tbody></table></div></Card>
 <Card className="mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><div className="font-bold">최근 6개월 추이</div><div className="mt-1 text-xs text-slate-500">월별 유입·매출·연체·재약정 흐름을 회의용으로 비교합니다.</div></div><div className="overflow-x-auto"><table className="admin-responsive-table w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{["월","신규 DB","신규 고객","계약 매출","실매출","연체 발생","재약정"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{trends.map(x=><tr key={x.month} className="border-t border-slate-100"><td className="px-4 py-3 font-bold">{x.month}</td><td className="px-4 py-3">{x.leads}건</td><td className="px-4 py-3">{x.customers}명</td><td className="px-4 py-3">{won(x.contractSales)}</td><td className="px-4 py-3 font-semibold text-blue-700">{won(x.realSales)}</td><td className="px-4 py-3">{x.overdue?<Badge tone="red">{x.overdue}건</Badge>:"0건"}</td><td className="px-4 py-3">{x.reschedules}건</td></tr>)}</tbody></table></div></Card>
 <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-xs leading-5 text-slate-500">계약·실매출·수금률·분납/연체 관련 수치는 전자서명 완료 고객 기준입니다. 현재 미수금은 전자서명 상태와 무관하게 등록된 계약금액에서 계약대금 실입금액을 차감해 집계합니다. 연체율은 선택 기간에 만기가 도래한 납부 일정 중 연체·미납 상태이거나 예정일보다 늦게 납부된 건을 기준으로 계산하며, 재약정 전 원 일정은 현재 예정매출/연체금액에 중복 계산하지 않습니다.</div>
 </>
}
