"use client";
import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {useRole} from "@/components/role-provider";

export type Manager=string;
export type PaymentStatus="예정"|"완료"|"연체"|"미납"|"환불";
export type RepaymentStatus="예정"|"상환완료"|"연체"|"보류"|"추심"|"종결";
export type ContactType=""|"번호"|"텔레그램"|"카카오톡"|"라인";
export type Customer={id:string;createdAt:string;createdTime?:string;name:string;phone:string;address:string;birthNumber:string;manager:Manager;coordinationManager:Manager;memo:string;contractDate:string;contractAmount:number;baseContractAmount?:number;prepaidAmount:number;basePrepaidAmount?:number;installmentMonths:number;lenderUnitPrice:number;lenderCount:number;baseLenderCount?:number;isAccident:boolean;legacyImported:boolean;accidentContractAmount?:number;accidentMarkedAt?:string;eformsignDocumentId?:string;eformsignStatus?:string;eformsignUpdatedAt?:string};
export type Payment={id:string;customerId:string;createdTime?:string;dueDate:string;dueAmount:number;paidDate:string;paidAmount:number;status:PaymentStatus;memo:string;paymentMethod?:string;settlementMemo?:string;scheduleType?:"일반"|"재약정"|"추가계약"|"환수";rootScheduleId?:string;rescheduledFromId?:string;rescheduleSequence?:number;sourceAdditionalContractId?:string;sourceRecoveryId?:string};
export type Repayment={id:string;customerId:string;createdTime?:string;lenderName:string;contactType:ContactType;contactValue:string;dueDate:string;amount:number;account:string;status:RepaymentStatus;memo:string};
export type LenderContact={id:string;type:ContactType;value:string};
export type Lender={id:string;createdAt:string;createdTime?:string;name:string;contacts:LenderContact[];account:string;memo:string;customerIds:string[]};
export type Attachment={id:string;name:string;size:number;type:string;storagePath:string};
export type BoardPost={id:string;createdTime?:string;title:string;body:string;writer:string;date:string;isNotice:boolean;noticeOrder:number;attachments:Attachment[]};
export type Settlement={id:string;createdTime?:string;paidDate:string;clientName:string;amount:number;paymentMethod:string;memo:string;customerId?:string;sourcePaymentScheduleId?:string;entrySource?:"manual"|"payment";entryType?:"계약"|"환수"};
export type MetaLeadRecord={id:string;createdAt:string;name:string;phone:string;manager:Manager;coordinationManager:Manager;lenderCount:number;memo:string;collectionIntensity:string;principalAmount:string;repaymentTotal:string;evidence:string;thirdPartyDamage:string;leadResult:string;status:"신규"|"고객등록완료";customerId:string|null};
export type AdditionalContract={id:string;customerId:string;createdTime?:string;contractDate:string;contractAmount:number;prepaidAmount:number;installmentMonths:number;lenderUnitPrice:number;lenderCount:number;isRenegotiation:boolean;memo:string};
export type Recovery={id:string;customerId:string;createdTime?:string;recoveryDate:string;lenderName:string;recoveryType:string;amount:number;paymentMethod:string;memo:string};
export type CustomerAdditionalContractRow=Omit<AdditionalContract,"id"|"customerId">&{id?:string};
export type CustomerRecoveryRow=Omit<Recovery,"id"|"customerId">&{id?:string};
export type CustomerPaymentRow=Omit<Payment,"id"|"customerId">&{id?:string};
export type CustomerRepaymentRow=Omit<Repayment,"id"|"customerId">&{id?:string};

type Store={
 loading:boolean;error:string|null;
 customers:Customer[];payments:Payment[];repayments:Repayment[];lenders:Lender[];posts:BoardPost[];settlements:Settlement[];metaLeads:MetaLeadRecord[];additionalContracts:AdditionalContract[];recoveries:Recovery[];
 refresh:()=>Promise<void>;
 addCustomer:(v:Omit<Customer,"id">)=>void;updateCustomer:(id:string,p:Partial<Customer>)=>void;deleteCustomer:(id:string)=>void;
 addPayment:(v:Omit<Payment,"id">)=>Promise<void>;addPayments:(rows:Omit<Payment,"id">[])=>Promise<void>;updatePayment:(id:string,p:Partial<Payment>)=>Promise<void>;deletePayment:(id:string)=>void;setCustomerPayments:(customerId:string,rows:CustomerPaymentRow[])=>Promise<void>;createRescheduledPayment:(fromId:string,v:{dueDate:string;dueAmount:number;memo:string})=>Promise<void>;
 addRepayment:(v:Omit<Repayment,"id">)=>void;updateRepayment:(id:string,p:Partial<Repayment>)=>void;deleteRepayment:(id:string)=>void;setCustomerRepayments:(customerId:string,rows:CustomerRepaymentRow[])=>Promise<void>;
 setCustomerAdditionalContracts:(customerId:string,rows:CustomerAdditionalContractRow[])=>Promise<void>;setCustomerRecoveries:(customerId:string,rows:CustomerRecoveryRow[])=>Promise<void>;
 addLender:(v:Omit<Lender,"id">)=>void;updateLender:(id:string,p:Partial<Lender>)=>void;deleteLender:(id:string)=>void;
 addPost:(v:Omit<BoardPost,"id">)=>void;updatePost:(id:string,p:Partial<BoardPost>)=>void;deletePost:(id:string)=>void;
 addSettlement:(v:Omit<Settlement,"id">)=>void;updateSettlement:(id:string,p:Partial<Settlement>)=>void;deleteSettlement:(id:string)=>void;resetSample:()=>void;
};

const supabase=createClient();
const Ctx=createContext<Store|null>(null);
const n=(v:unknown)=>Number(v||0);
const date=(v:unknown)=>String(v||"").slice(0,10);
const fail=(message:string)=>{console.error(message);if(typeof window!=="undefined")alert(message)};

export function AdminStoreProvider({children}:{children:React.ReactNode}){
 const {isAdmin}=useRole();
 const [customers,setCustomers]=useState<Customer[]>([]);const [payments,setPayments]=useState<Payment[]>([]);const [repayments,setRepayments]=useState<Repayment[]>([]);const [lenders,setLenders]=useState<Lender[]>([]);const [posts,setPosts]=useState<BoardPost[]>([]);const [settlements,setSettlements]=useState<Settlement[]>([]);const [metaLeads,setMetaLeads]=useState<MetaLeadRecord[]>([]);const [additionalContracts,setAdditionalContracts]=useState<AdditionalContract[]>([]);const [recoveries,setRecoveries]=useState<Recovery[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const initializedRef=useRef(false);
 const requireAdmin=(action="이 작업")=>{if(isAdmin)return true;fail(`${action}은(는) 최종관리자만 가능합니다.`);return false};

 const refresh=useCallback(async()=>{
  if(!initializedRef.current)setLoading(true);setError(null);
  const [cu,pa,re,le,lc,lcu,po,at,se,me,ac,rv]=await Promise.all([
   supabase.from("customers").select("*").is("deleted_at",null).order("admin_created_at",{ascending:false}).order("id",{ascending:false}),
   supabase.from("payment_schedules").select("*").is("deleted_at",null).order("due_date",{ascending:false}).order("admin_created_at",{ascending:false}).order("id",{ascending:false}),
   supabase.from("repayment_schedules").select("*").is("deleted_at",null).order("repayment_date",{ascending:false}).order("admin_created_at",{ascending:false}).order("id",{ascending:false}),
   supabase.from("lenders").select("*").is("deleted_at",null).order("admin_created_at",{ascending:false}).order("id",{ascending:false}),
   supabase.from("lender_contacts").select("*").order("sort_order",{ascending:true}),
   supabase.from("lender_customers").select("lender_id,customer_id"),
   supabase.from("board_posts").select("*").is("deleted_at",null).order("admin_created_at",{ascending:false}).order("id",{ascending:false}),
   supabase.from("board_attachments").select("*").order("created_at",{ascending:true}),
   supabase.from("settlement_entries").select("*").is("deleted_at",null).order("payment_date",{ascending:false}).order("admin_created_at",{ascending:false}).order("id",{ascending:false}),
   supabase.from("meta_leads").select("*").order("created_at",{ascending:false}).order("id",{ascending:false}),
   supabase.from("additional_contracts").select("*").is("deleted_at",null).order("admin_created_at",{ascending:false}).order("id",{ascending:false}),
   supabase.from("recoveries").select("*").is("deleted_at",null).order("recovery_date",{ascending:false}).order("admin_created_at",{ascending:false}).order("id",{ascending:false}),
  ]);
  const firstError=[cu,pa,re,le,lc,lcu,po,at,se,me,ac,rv].find(x=>x.error)?.error;
  if(firstError){setError(firstError.message);setLoading(false);return}
  const additionalRows:AdditionalContract[]=(ac.data||[]).map((x:any)=>({id:x.id,customerId:x.customer_id,createdTime:x.admin_created_at||"",contractDate:date(x.contract_date),contractAmount:n(x.contract_amount),prepaidAmount:n(x.upfront_amount),installmentMonths:n(x.installment_period),lenderUnitPrice:n(x.lender_unit_price),lenderCount:n(x.lender_count),isRenegotiation:!!x.is_renegotiation,memo:x.memo||""}));
  const recoveryRows:Recovery[]=(rv.data||[]).map((x:any)=>({id:x.id,customerId:x.customer_id,createdTime:x.admin_created_at||"",recoveryDate:date(x.recovery_date),lenderName:x.lender_name||"",recoveryType:x.recovery_type||"",amount:n(x.amount),paymentMethod:x.payment_method||"계좌이체",memo:x.memo||""}));
  setAdditionalContracts(additionalRows);setRecoveries(recoveryRows);
  setCustomers((cu.data||[]).map((x:any)=>{const extras=additionalRows.filter(a=>a.customerId===x.id);const extraContract=extras.reduce((sum,a)=>sum+a.contractAmount,0);const extraPrepaid=extras.reduce((sum,a)=>sum+a.prepaidAmount,0);const extraLenders=extras.filter(a=>!a.isRenegotiation).reduce((sum,a)=>sum+a.lenderCount,0);const baseContract=n(x.contract_amount),basePrepaid=n(x.upfront_amount),baseLenders=n(x.lender_count);const isAccident=!!x.is_accident;const accidentContractAmount=x.accident_contract_amount===null||x.accident_contract_amount===undefined?undefined:n(x.accident_contract_amount);return{id:x.id,createdAt:date(x.registered_at),createdTime:x.admin_created_at||x.registered_at||"",name:x.name||"",phone:x.phone||"",address:x.address||"",birthNumber:x.birth_number||"",manager:(x.sales_manager||x.manager||"신홍규") as Manager,coordinationManager:(x.coordination_manager||"신홍규") as Manager,memo:x.memo||"",contractDate:date(x.contract_date),contractAmount:isAccident?(accidentContractAmount??0):baseContract+extraContract,baseContractAmount:baseContract,prepaidAmount:basePrepaid+extraPrepaid,basePrepaidAmount:basePrepaid,installmentMonths:n(x.installment_period),lenderUnitPrice:n(x.lender_unit_price),lenderCount:baseLenders+extraLenders,baseLenderCount:baseLenders,isAccident,legacyImported:!!x.legacy_imported,accidentContractAmount,accidentMarkedAt:x.accident_marked_at||"",eformsignDocumentId:x.eformsign_document_id||"",eformsignStatus:x.eformsign_status||"",eformsignUpdatedAt:x.eformsign_updated_at||""}}));
  setPayments((pa.data||[]).map((x:any)=>({id:x.id,customerId:x.customer_id,createdTime:x.admin_created_at||"",dueDate:date(x.due_date),dueAmount:n(x.expected_amount),paidDate:date(x.paid_date),paidAmount:n(x.paid_amount),status:(x.status||"예정") as PaymentStatus,memo:x.memo||"",paymentMethod:x.payment_method||"계좌이체",settlementMemo:"",scheduleType:(x.schedule_type||"일반") as "일반"|"재약정"|"추가계약"|"환수",rootScheduleId:x.root_schedule_id||x.id,rescheduledFromId:x.rescheduled_from_id||"",rescheduleSequence:n(x.reschedule_sequence),sourceAdditionalContractId:x.source_additional_contract_id||"",sourceRecoveryId:x.source_recovery_id||""})));
  setRepayments((re.data||[]).map((x:any)=>({id:x.id,customerId:x.customer_id,createdTime:x.admin_created_at||"",lenderName:x.lender_name||"",contactType:(x.lender_contact_type||"") as ContactType,contactValue:x.lender_contact_value||"",dueDate:date(x.repayment_date),amount:n(x.repayment_amount),account:x.account_info||"",status:(x.status==="완료"?"상환완료":(x.status||"예정")) as RepaymentStatus,memo:x.memo||""})));
  const contactRows=(lc.data||[]) as any[];
  const lenderCustomerRows=(lcu.data||[]) as any[];
  setLenders((le.data||[]).map((x:any)=>({id:x.id,createdAt:date(x.created_at),createdTime:x.admin_created_at||x.created_at||"",name:x.name||"",account:x.account_info||"",memo:x.memo||"",contacts:contactRows.filter(c=>c.lender_id===x.id).map(c=>({id:c.id,type:c.contact_type as ContactType,value:c.contact_value||""})),customerIds:lenderCustomerRows.filter(r=>r.lender_id===x.id).map(r=>r.customer_id)})));
  const attachmentRows=(at.data||[]) as any[];
  setPosts((po.data||[]).map((x:any)=>({id:x.id,createdTime:x.admin_created_at||x.post_date||"",title:x.title||"",body:x.body||"",writer:x.author||"",date:date(x.post_date),isNotice:!!x.is_notice,noticeOrder:n(x.notice_order),attachments:attachmentRows.filter(a=>a.post_id===x.id).map(a=>({id:a.id,name:a.file_name,size:n(a.file_size),type:a.mime_type||"",storagePath:a.storage_path||""}))})));
  setSettlements((se.data||[]).map((x:any)=>({id:x.id,createdTime:x.admin_created_at||"",paidDate:date(x.payment_date),clientName:x.client_name||"",amount:n(x.amount),paymentMethod:x.payment_method||"계좌이체",memo:x.memo||"",customerId:x.customer_id||"",sourcePaymentScheduleId:x.source_payment_schedule_id||"",entrySource:(x.entry_source||"manual") as "manual"|"payment",entryType:(x.entry_type||"계약") as "계약"|"환수"})));
  setMetaLeads((me.data||[]).map((x:any)=>({id:x.id,createdAt:x.created_at||"",name:x.customer_name||"",phone:x.phone_number||"",manager:(x.sales_manager||x.manager||"신홍규") as Manager,coordinationManager:(x.coordination_manager||"신홍규") as Manager,lenderCount:n(x.lender_count),memo:x.memo||"",collectionIntensity:x.collection_intensity||"",principalAmount:String(x.principal_amount??""),repaymentTotal:String(x.repayment_total??""),evidence:x.evidence||"",thirdPartyDamage:x.third_party_damage||"",leadResult:x.lead_result||"미분류",status:x.status==="고객등록완료"?"고객등록완료":"신규",customerId:x.customer_id||null})));
  initializedRef.current=true;
  setLoading(false);
 },[]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{
  const realtimeTables=["customers","payment_schedules","repayment_schedules","lenders","lender_contacts","lender_customers","board_posts","board_attachments","settlement_entries","meta_leads","additional_contracts","recoveries","change_history","negotiation_guidelines","customer_calculator_items","customer_calculation_snapshots"];
  const storeTables=new Set(["customers","payment_schedules","repayment_schedules","lenders","lender_contacts","lender_customers","board_posts","board_attachments","settlement_entries","meta_leads","additional_contracts","recoveries"]);
  let timer:ReturnType<typeof setTimeout>|null=null;
  let pendingAutoRefresh=false;
  const isEditing=()=>{
   if(typeof document==="undefined")return false;
   if(document.querySelector('[data-admin-edit-lock="true"]'))return true;
   const active=document.activeElement as HTMLElement|null;
   return !!active&&(active.tagName==="INPUT"||active.tagName==="TEXTAREA"||active.tagName==="SELECT"||active.isContentEditable);
  };
  const runAutoRefresh=()=>{if(isEditing()){pendingAutoRefresh=true;return}pendingAutoRefresh=false;void refresh()};
  const flushPending=()=>{if(!pendingAutoRefresh)return;window.setTimeout(()=>{if(pendingAutoRefresh&&!isEditing()){pendingAutoRefresh=false;void refresh()}},0)};
  const scheduleRefresh=()=>{if(timer)clearTimeout(timer);timer=setTimeout(runAutoRefresh,120)};
  const handleChange=(payload:any)=>{const table=String(payload?.table||"");if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("admin:data-changed",{detail:{table,eventType:String(payload?.eventType||"")}}));if(storeTables.has(table))scheduleRefresh()};
  let channel=supabase.channel("admin-live-v23");
  for(const table of realtimeTables)channel=channel.on("postgres_changes",{event:"*",schema:"public",table},handleChange);
  channel.subscribe();
  const fallback=window.setInterval(runAutoRefresh,30000);
  window.addEventListener("admin:edit-lock-changed",flushPending);
  document.addEventListener("focusout",flushPending,true);
  return()=>{if(timer)clearTimeout(timer);window.clearInterval(fallback);window.removeEventListener("admin:edit-lock-changed",flushPending);document.removeEventListener("focusout",flushPending,true);void supabase.removeChannel(channel)};
 },[refresh]);

 async function syncLendersFromRepayments(rows:Array<{customerId:string;lenderName:string;contactType:ContactType;contactValue:string;account:string}>) {
  // 업체명 + 연락수단 + 연락정보가 모두 같은 경우에만 동일 업체로 판단합니다.
  // 같은 고객이 같은 업체로 여러 상환일정을 한 번에 저장해도 사채업체 관리에는 1건만 추가됩니다.
  const normalizeContact=(value:string)=>String(value||"").replace(/\s+/g,"");
  const keyOf=(name:string,type:ContactType,value:string)=>`${name.trim()}\u0000${type}\u0000${normalizeContact(value)}`;
  const known=new Map<string,string>();
  for(const lender of lenders){
   if(lender.contacts.length){
    for(const contact of lender.contacts){
     const contactValue=(contact.value||"").trim();
     if(contactValue)known.set(keyOf(lender.name,contact.type,contactValue),lender.id);
    }
   }
  }
  for(const row of rows){
   const name=(row.lenderName||"").trim();
   const value=(row.contactValue||"").trim();
   const type=row.contactType;
   if(!name&&!value&&!(row.account||"").trim())continue;
   const key=keyOf(name,type,value);
   // 연락정보가 비어 있으면 중복검사를 하지 않고 무조건 신규 등록합니다.
   if(value&&known.has(key)){
    const lenderId=known.get(key)!;
    if(row.customerId){const link=await supabase.from("lender_customers").upsert({lender_id:lenderId,customer_id:row.customerId},{onConflict:"lender_id,customer_id",ignoreDuplicates:true});if(link.error)fail(link.error.message)}
    continue;
   }

   const created=await supabase.from("lenders").insert({name,account_info:row.account||null,memo:"상환 일정에서 자동 등록",created_at:todayIso()}).select("id").single();
   if(created.error){fail(created.error.message);continue}
   if(type){
    const ins=await supabase.from("lender_contacts").insert({lender_id:created.data.id,contact_type:type,contact_value:value,sort_order:0});
    if(ins.error){fail(ins.error.message);continue}
   }
   if(type&&value)known.set(key,created.data.id);
   if(row.customerId){const link=await supabase.from("lender_customers").upsert({lender_id:created.data.id,customer_id:row.customerId},{onConflict:"lender_id,customer_id",ignoreDuplicates:true});if(link.error)fail(link.error.message)}
  }
 }
 const repaymentPayload=(v:Omit<Repayment,"id">|Repayment)=>({lender_name:v.lenderName,lender_contact_type:v.contactType||null,lender_contact_value:v.contactValue||null,repayment_date:v.dueDate||null,repayment_amount:v.status==="종결"?0:v.amount,account_info:v.account,status:v.status,memo:v.memo});
 const legacyCompletedPayload=(payload:ReturnType<typeof repaymentPayload>)=>payload.status==="상환완료"?{...payload,status:"완료"}:payload;
 const isStatusConstraintError=(message?:string)=>!!message&&message.includes("repayment_schedules_status_check");
 const todayIso=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
 const paymentPayload=(v:Omit<Payment,"id">|Payment)=>({customer_id:v.customerId,due_date:v.dueDate||null,expected_amount:v.dueAmount,paid_date:v.paidDate||null,paid_amount:v.paidAmount,status:v.status,payment_method:v.paymentMethod||null,memo:v.memo,schedule_type:v.scheduleType||"일반",root_schedule_id:v.rootScheduleId||null,rescheduled_from_id:v.rescheduledFromId||null,reschedule_sequence:v.rescheduleSequence||0,source_additional_contract_id:v.sourceAdditionalContractId||null,source_recovery_id:v.sourceRecoveryId||null});

 const value=useMemo<Store>(()=>({loading,error,customers,payments,repayments,lenders,posts,settlements,metaLeads,additionalContracts,recoveries,refresh,
  addCustomer(v){void (async()=>{const initialAccidentAmount=v.isAccident?(v.prepaidAmount||0):null;const {data,error}=await supabase.from("customers").insert({registered_at:v.createdAt,name:v.name,phone:v.phone,address:v.address||null,birth_number:v.birthNumber||null,manager:v.manager,sales_manager:v.manager,coordination_manager:v.coordinationManager,memo:v.memo,contract_date:v.contractDate||null,contract_amount:v.contractAmount,upfront_amount:v.prepaidAmount,installment_period:v.installmentMonths,lender_unit_price:v.lenderUnitPrice,lender_count:v.lenderCount,is_accident:!!v.isAccident,legacy_imported:!!v.legacyImported,accident_contract_amount:initialAccidentAmount,accident_marked_at:v.isAccident?new Date().toISOString():null}).select("id").single();if(error)return fail(error.message);if(v.prepaidAmount>0){const paidDate=v.contractDate||v.createdAt;const p=await supabase.from("payment_schedules").insert({customer_id:data.id,due_date:paidDate,expected_amount:v.prepaidAmount,paid_date:paidDate,paid_amount:v.prepaidAmount,status:"완료",payment_method:"계좌이체",memo:"고객 등록 시 선납금 자동 반영"});if(p.error)return fail(p.error.message)}await refresh()})()},
  updateCustomer(id,p){void (async()=>{const cur=customers.find(x=>x.id===id);if(!cur)return;const v={...cur,...p};const nextIsAccident=!!v.isAccident;const newlyAccident=!cur.isAccident&&nextIsAccident;const accidentPaid=payments.filter(row=>row.customerId===id&&row.status!=="환불"&&row.scheduleType!=="환수").reduce((sum,row)=>sum+(row.paidAmount||0),0);const accidentContractAmount=nextIsAccident?(newlyAccident?accidentPaid:(cur.accidentContractAmount??accidentPaid)):null;const accidentMarkedAt=nextIsAccident?(newlyAccident?new Date().toISOString():(cur.accidentMarkedAt||new Date().toISOString())):null;const {error}=await supabase.from("customers").update({registered_at:v.createdAt,name:v.name,phone:v.phone,address:v.address||null,birth_number:v.birthNumber||null,manager:v.manager,sales_manager:v.manager,coordination_manager:v.coordinationManager,memo:v.memo,contract_date:v.contractDate||null,contract_amount:v.contractAmount,upfront_amount:v.prepaidAmount,installment_period:v.installmentMonths,lender_unit_price:v.lenderUnitPrice,lender_count:v.lenderCount,is_accident:nextIsAccident,legacy_imported:!!v.legacyImported,accident_contract_amount:accidentContractAmount,accident_marked_at:accidentMarkedAt}).eq("id",id);if(error)return fail(error.message);await refresh()})()},
  deleteCustomer(id){if(!requireAdmin("고객 삭제"))return;void (async()=>{const {error}=await supabase.from("customers").update({deleted_at:new Date().toISOString()}).eq("id",id);if(error)return fail(error.message);await refresh()})()},
  async addPayment(v){const {error}=await supabase.from("payment_schedules").insert(paymentPayload(v));if(error){fail(error.message);return}await refresh()},
  async addPayments(rows){if(!rows.length)return;const {error}=await supabase.from("payment_schedules").insert(rows.map(paymentPayload));if(error){fail(error.message);return}await refresh()},
  async updatePayment(id,p){const cur=payments.find(x=>x.id===id);if(!cur)return;if(cur.sourceRecoveryId||cur.scheduleType==="추가계약"||cur.sourceAdditionalContractId){fail(cur.sourceRecoveryId?"환수 등록에서 자동 연동된 건은 고객정보의 환수 등록에서 수정해주세요.":"추가 계약 선납금은 고객정보의 추가 계약에서 수정해주세요.");return}const v={...cur,...p};const {customer_id,...payload}=paymentPayload(v);void customer_id;const {error}=await supabase.from("payment_schedules").update(payload).eq("id",id);if(error){fail(error.message);return}await refresh()},
  deletePayment(id){if(!requireAdmin("입금/분납 삭제"))return;void (async()=>{const target=payments.find(p=>p.id===id);if(target&&(target.sourceRecoveryId||target.scheduleType==="추가계약"||target.sourceAdditionalContractId))return fail(target.sourceRecoveryId?"환수 등록에서 자동 연동된 건은 고객정보의 환수 등록에서 삭제해주세요.":"추가 계약 선납금은 고객정보의 추가 계약에서 삭제해주세요.");if(payments.some(p=>p.rescheduledFromId===id))return fail("재약정 이력이 연결된 납부 일정은 삭제할 수 없습니다. 연체 통계 보존을 위해 원 일정이 유지됩니다.");const {error}=await supabase.from("payment_schedules").update({deleted_at:new Date().toISOString()}).eq("id",id);if(error)return fail(error.message);await refresh()})()},
  async setCustomerPayments(customerId,rows){const isSystemManaged=(p:Payment)=>!!p.sourceRecoveryId||p.scheduleType==="추가계약"||!!p.sourceAdditionalContractId;const existing=payments.filter(p=>p.customerId===customerId&&!isSystemManaged(p));const keepIds=new Set(rows.map(r=>r.id).filter(Boolean) as string[]);const removeIds=existing.filter(p=>!keepIds.has(p.id)).map(p=>p.id);const protectedIds=removeIds.filter(id=>payments.some(p=>p.rescheduledFromId===id));if(protectedIds.length){fail("재약정 이력이 연결된 과거 납부 일정은 삭제할 수 없습니다. 연체 통계 보존을 위해 해당 일정을 유지해주세요.");return}if(removeIds.length&&!isAdmin){fail("입금/분납 삭제는 최종관리자만 가능합니다.");return}if(removeIds.length){const d=await supabase.from("payment_schedules").update({deleted_at:new Date().toISOString()}).in("id",removeIds);if(d.error){fail(d.error.message);return}}for(const row of rows){if(row.id){const cur=existing.find(p=>p.id===row.id);if(!cur)continue;const v:Payment={...cur,...row,id:row.id,customerId};const {customer_id,...payload}=paymentPayload(v);void customer_id;const u=await supabase.from("payment_schedules").update(payload).eq("id",row.id);if(u.error){fail(u.error.message);return}}else{const {id:_rowId,...rest}=row;void _rowId;const v:Omit<Payment,"id">={customerId,...rest};const i=await supabase.from("payment_schedules").insert(paymentPayload(v));if(i.error){fail(i.error.message);return}}}await refresh()},
  async createRescheduledPayment(fromId,v){const from=payments.find(p=>p.id===fromId);if(!from)return fail("원 납부일정을 찾지 못했습니다.");const existingChild=payments.find(p=>p.rescheduledFromId===fromId);if(existingChild)return fail(`이미 다음 납부 예정일(${existingChild.dueDate})이 등록되어 있습니다.`);const remaining=Math.max(0,v.dueAmount);const payload={customer_id:from.customerId,due_date:v.dueDate||null,expected_amount:remaining,paid_date:null,paid_amount:0,status:"예정",payment_method:from.paymentMethod||"계좌이체",memo:v.memo||"연체 후 재약정",schedule_type:"재약정",root_schedule_id:from.rootScheduleId||from.id,rescheduled_from_id:from.id,reschedule_sequence:(from.rescheduleSequence||0)+1};const {error}=await supabase.from("payment_schedules").insert(payload);if(error){fail(error.message);return}await refresh()},
  addRepayment(v){void (async()=>{const payload={customer_id:v.customerId,...repaymentPayload(v)};let result=await supabase.from("repayment_schedules").insert(payload);if(result.error&&v.status==="상환완료"&&isStatusConstraintError(result.error.message))result=await supabase.from("repayment_schedules").insert({customer_id:v.customerId,...legacyCompletedPayload(repaymentPayload(v))});if(result.error)return fail(result.error.message);await syncLendersFromRepayments([v]);await refresh()})()},
  updateRepayment(id,p){void (async()=>{const cur=repayments.find(x=>x.id===id);if(!cur)return;const v={...cur,...p};let result=await supabase.from("repayment_schedules").update(repaymentPayload(v)).eq("id",id);if(result.error&&v.status==="상환완료"&&isStatusConstraintError(result.error.message))result=await supabase.from("repayment_schedules").update(legacyCompletedPayload(repaymentPayload(v))).eq("id",id);if(result.error)return fail(result.error.message);const lenderChanged=cur.lenderName!==v.lenderName||cur.contactType!==v.contactType||cur.contactValue!==v.contactValue||cur.account!==v.account;if(lenderChanged)await syncLendersFromRepayments([v]);await refresh()})()},
  deleteRepayment(id){if(!requireAdmin("상환일정 삭제"))return;void (async()=>{const {error}=await supabase.from("repayment_schedules").update({deleted_at:new Date().toISOString()}).eq("id",id);if(error)return fail(error.message);await refresh()})()},
  async setCustomerRepayments(customerId,rows){const existing=repayments.filter(r=>r.customerId===customerId);const keepIds=new Set(rows.map(r=>r.id).filter(Boolean) as string[]);const removeIds=existing.filter(r=>!keepIds.has(r.id)).map(r=>r.id);if(removeIds.length&&!isAdmin){fail("상환일정 삭제는 최종관리자만 가능합니다.");return}if(removeIds.length){const d=await supabase.from("repayment_schedules").update({deleted_at:new Date().toISOString()}).in("id",removeIds);if(d.error){fail(d.error.message);return}}const lenderSyncRows:Array<CustomerRepaymentRow&{customerId:string}>=[];for(const row of rows){if(row.id){const cur=existing.find(r=>r.id===row.id);if(!cur)continue;const v:Repayment={...cur,...row,id:row.id,customerId};let result=await supabase.from("repayment_schedules").update(repaymentPayload(v)).eq("id",row.id);if(result.error&&v.status==="상환완료"&&isStatusConstraintError(result.error.message))result=await supabase.from("repayment_schedules").update(legacyCompletedPayload(repaymentPayload(v))).eq("id",row.id);if(result.error){fail(result.error.message);return}if(cur.lenderName!==v.lenderName||cur.contactType!==v.contactType||cur.contactValue!==v.contactValue||cur.account!==v.account)lenderSyncRows.push({...row,customerId})}else{const {id:_rowId,...rest}=row;void _rowId;const v:Repayment={id:"",customerId,...rest};let result=await supabase.from("repayment_schedules").insert({customer_id:customerId,...repaymentPayload(v)});if(result.error&&v.status==="상환완료"&&isStatusConstraintError(result.error.message))result=await supabase.from("repayment_schedules").insert({customer_id:customerId,...legacyCompletedPayload(repaymentPayload(v))});if(result.error){fail(result.error.message);return}lenderSyncRows.push({...row,customerId})}}if(lenderSyncRows.length)await syncLendersFromRepayments(lenderSyncRows);await refresh()},
  async setCustomerAdditionalContracts(customerId,rows){const existing=additionalContracts.filter(x=>x.customerId===customerId);const keepIds=new Set(rows.map(x=>x.id).filter(Boolean) as string[]);const removeIds=existing.filter(x=>!keepIds.has(x.id)).map(x=>x.id);if(removeIds.length&&!isAdmin){fail("추가계약 삭제는 최종관리자만 가능합니다.");return}if(removeIds.length){const d=await supabase.from("additional_contracts").update({deleted_at:new Date().toISOString()}).in("id",removeIds);if(d.error){fail(d.error.message);return}}for(const row of rows){const payload={customer_id:customerId,contract_date:row.contractDate||null,contract_amount:row.contractAmount||0,upfront_amount:row.isRenegotiation?0:(row.prepaidAmount||0),installment_period:row.isRenegotiation?0:(row.installmentMonths||0),lender_unit_price:row.lenderUnitPrice||0,lender_count:row.lenderCount||0,is_renegotiation:!!row.isRenegotiation,memo:row.memo||""};if(row.id){const u=await supabase.from("additional_contracts").update(payload).eq("id",row.id);if(u.error){fail(u.error.message);return}}else{const i=await supabase.from("additional_contracts").insert(payload);if(i.error){fail(i.error.message);return}}}await refresh()},
  async setCustomerRecoveries(customerId,rows){const existing=recoveries.filter(x=>x.customerId===customerId);const keepIds=new Set(rows.map(x=>x.id).filter(Boolean) as string[]);const removeIds=existing.filter(x=>!keepIds.has(x.id)).map(x=>x.id);if(removeIds.length&&!isAdmin){fail("환수 삭제는 최종관리자만 가능합니다.");return}if(removeIds.length){const d=await supabase.from("recoveries").update({deleted_at:new Date().toISOString()}).in("id",removeIds);if(d.error){fail(d.error.message);return}}for(const row of rows){const payload={customer_id:customerId,recovery_date:row.recoveryDate||null,lender_name:row.lenderName||"",recovery_type:row.recoveryType||"",amount:row.amount||0,payment_method:row.paymentMethod||"계좌이체",memo:row.memo||""};if(row.id){const u=await supabase.from("recoveries").update(payload).eq("id",row.id);if(u.error){fail(u.error.message);return}}else{const i=await supabase.from("recoveries").insert(payload);if(i.error){fail(i.error.message);return}}}await refresh()},
  addLender(v){void (async()=>{const norm=(x:string)=>String(x||"").trim();const normContact=(x:string)=>String(x||"").replace(/\s+/g,"");const duplicate=v.contacts.some(contact=>{const contactValue=normContact(contact.value);if(!contactValue)return false;return lenders.some(l=>norm(l.name)===norm(v.name)&&l.contacts.some(c=>c.type===contact.type&&normContact(c.value)===contactValue))});if(duplicate)return fail("업체명, 연락수단, 공백을 제외한 연락정보가 모두 같은 업체가 이미 등록되어 있습니다.");const {data,error}=await supabase.from("lenders").insert({name:v.name,account_info:v.account||null,memo:v.memo,created_at:v.createdAt||undefined}).select("id").single();if(error)return fail(error.message);if(v.contacts.length){const c=await supabase.from("lender_contacts").insert(v.contacts.map((x,i)=>({lender_id:data.id,contact_type:x.type,contact_value:x.value||"",sort_order:i})));if(c.error)return fail(c.error.message)}if(v.customerIds?.length){const links=await supabase.from("lender_customers").insert(v.customerIds.map(customerId=>({lender_id:data.id,customer_id:customerId})));if(links.error)return fail(links.error.message)}await refresh()})()},
  updateLender(id,p){void (async()=>{const cur=lenders.find(x=>x.id===id);if(!cur)return;const v={...cur,...p};const u=await supabase.from("lenders").update({name:v.name,account_info:v.account||null,memo:v.memo,created_at:v.createdAt||undefined}).eq("id",id);if(u.error)return fail(u.error.message);const d=await supabase.from("lender_contacts").delete().eq("lender_id",id);if(d.error)return fail(d.error.message);if(v.contacts.length){const c=await supabase.from("lender_contacts").insert(v.contacts.map((x,i)=>({lender_id:id,contact_type:x.type,contact_value:x.value||"",sort_order:i})));if(c.error)return fail(c.error.message)}const oldCustomerIds=new Set(cur.customerIds||[]);const nextCustomerIds=new Set(v.customerIds||[]);const removed=[...oldCustomerIds].filter(customerId=>!nextCustomerIds.has(customerId));const added=[...nextCustomerIds].filter(customerId=>!oldCustomerIds.has(customerId));if(removed.length){const dl=await supabase.from("lender_customers").delete().eq("lender_id",id).in("customer_id",removed);if(dl.error)return fail(dl.error.message)}if(added.length){const links=await supabase.from("lender_customers").insert(added.map(customerId=>({lender_id:id,customer_id:customerId})));if(links.error)return fail(links.error.message)}await refresh()})()},
  deleteLender(id){if(!requireAdmin("사채업체 삭제"))return;void (async()=>{const {error}=await supabase.from("lenders").update({deleted_at:new Date().toISOString()}).eq("id",id);if(error)return fail(error.message);await refresh()})()},
  addPost(v){void (async()=>{const {data,error}=await supabase.from("board_posts").insert({title:v.title,body:v.body,author:v.writer,post_date:v.date,is_notice:v.isNotice,notice_order:v.noticeOrder}).select("id").single();if(error)return fail(error.message);if(v.attachments.length){const a=await supabase.from("board_attachments").insert(v.attachments.map(x=>({post_id:data.id,file_name:x.name,storage_path:x.storagePath,file_size:x.size,mime_type:x.type})));if(a.error)return fail(a.error.message)}await refresh()})()},
  updatePost(id,p){void (async()=>{const cur=posts.find(x=>x.id===id);if(!cur)return;const v={...cur,...p};const u=await supabase.from("board_posts").update({title:v.title,body:v.body,author:v.writer,post_date:v.date,is_notice:v.isNotice,notice_order:v.noticeOrder}).eq("id",id);if(u.error)return fail(u.error.message);const d=await supabase.from("board_attachments").delete().eq("post_id",id);if(d.error)return fail(d.error.message);if(v.attachments.length){const a=await supabase.from("board_attachments").insert(v.attachments.map(x=>({post_id:id,file_name:x.name,storage_path:x.storagePath,file_size:x.size,mime_type:x.type})));if(a.error)return fail(a.error.message)}await refresh()})()},
  deletePost(id){if(!requireAdmin("게시글 삭제"))return;void (async()=>{const post=posts.find(x=>x.id===id);if(post?.attachments.length)await supabase.storage.from("board-files").remove(post.attachments.map(a=>a.storagePath));const {error}=await supabase.from("board_posts").delete().eq("id",id);if(error)return fail(error.message);await refresh()})()},
  addSettlement(v){void (async()=>{const {error}=await supabase.from("settlement_entries").insert({payment_date:v.paidDate,client_name:v.clientName,amount:v.amount,payment_method:v.paymentMethod,memo:v.memo,entry_source:"manual",entry_type:"계약"});if(error)return fail(error.message);await refresh()})()},
  updateSettlement(id,p){void (async()=>{const cur=settlements.find(x=>x.id===id);if(!cur)return;if(cur.entrySource==="payment")return fail("자동 연동된 정산 내역은 입금/분납 관리에서 수정해주세요.");const v={...cur,...p};const {error}=await supabase.from("settlement_entries").update({payment_date:v.paidDate,client_name:v.clientName,amount:v.amount,payment_method:v.paymentMethod,memo:v.memo}).eq("id",id);if(error)return fail(error.message);await refresh()})()},
  deleteSettlement(id){if(!requireAdmin("정산 삭제"))return;void (async()=>{const cur=settlements.find(x=>x.id===id);if(cur?.entrySource==="payment")return fail("자동 연동된 정산 내역은 원본 입금/분납 건을 삭제하거나 완료 상태를 해제해주세요.");const {error}=await supabase.from("settlement_entries").update({deleted_at:new Date().toISOString()}).eq("id",id);if(error)return fail(error.message);await refresh()})()},
  resetSample(){void refresh()}
 }),[loading,error,customers,payments,repayments,lenders,posts,settlements,metaLeads,additionalContracts,recoveries,refresh,isAdmin]);
 return <Ctx.Provider value={value}>{loading&&!initializedRef.current?<div className="grid min-h-screen place-items-center bg-slate-50 text-sm font-semibold text-slate-500">데이터를 불러오는 중입니다...</div>:error&&!initializedRef.current?<div className="grid min-h-screen place-items-center bg-slate-50 p-6"><div className="max-w-xl rounded-xl border border-red-200 bg-white p-6 text-sm text-red-700"><b>Supabase 연결 오류</b><div className="mt-2 break-all">{error}</div><button className="mt-4 rounded-lg bg-blue-600 px-3 py-2 text-white" onClick={()=>void refresh()}>다시 시도</button></div></div>:children}</Ctx.Provider>;
}
export function useAdminStore(){const x=useContext(Ctx);if(!x)throw new Error("AdminStoreProvider missing");return x}
