import {useEffect,useRef,useState} from "react";
import { cn } from "@/lib/utils";
export function Card({className,children}:{className?:string;children:React.ReactNode}) { return <div className={cn("rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,.03)]",className)}>{children}</div> }
export function Button({className,variant="primary",children,onClick,type="button",disabled=false}:{className?:string;variant?:"primary"|"secondary"|"ghost"|"danger";children:React.ReactNode;onClick?:(event:React.MouseEvent<HTMLButtonElement>)=>void|Promise<void>;type?:"button"|"submit";disabled?:boolean}) { const styles={primary:"bg-blue-600 text-white hover:bg-blue-700",secondary:"border border-slate-200 bg-white text-slate-700 hover:bg-slate-50",ghost:"text-slate-600 hover:bg-slate-100",danger:"bg-red-50 text-red-700 hover:bg-red-100"}; const [clickBusy,setClickBusy]=useState(false);const lockRef=useRef(false);async function handleClick(event:React.MouseEvent<HTMLButtonElement>){if(disabled||lockRef.current){event.preventDefault();return}lockRef.current=true;setClickBusy(true);const started=Date.now();try{await onClick?.(event)}finally{const delay=Math.max(0,1000-(Date.now()-started));window.setTimeout(()=>{lockRef.current=false;setClickBusy(false)},delay)}} return <button type={type} onClick={onClick?handleClick:undefined} disabled={disabled||clickBusy} className={cn("inline-flex h-10 shrink-0 touch-manipulation items-center justify-center gap-2 whitespace-nowrap rounded-lg px-3 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 sm:h-9",styles[variant],className)}>{children}</button> }
export function Badge({children,tone="gray"}:{children:React.ReactNode;tone?:"gray"|"blue"|"green"|"red"|"amber"}) { const map={gray:"bg-slate-100 text-slate-600",blue:"bg-blue-50 text-blue-700",green:"bg-emerald-50 text-emerald-700",red:"bg-red-50 text-red-700",amber:"bg-amber-50 text-amber-700"}; return <span className={cn("inline-flex shrink-0 whitespace-nowrap rounded-md px-2 py-1 text-xs font-semibold",map[tone])}>{children}</span> }
export function PageHeader({title,description,action}:{title:string;description:string;action?:React.ReactNode}) { return <div className="mb-4 flex flex-col justify-between gap-3 sm:mb-5 lg:flex-row lg:items-end"><div className="min-w-0"><h1 className="text-xl font-bold tracking-tight text-slate-900 sm:text-2xl">{title}</h1><p className="mt-1 break-keep text-[13px] leading-5 text-slate-500 sm:text-sm">{description}</p></div>{action&&<div className="w-full lg:w-auto">{action}</div>}</div> }
export function Input({value,onChange,placeholder,type="text",className}:{value?:string;onChange?:(e:React.ChangeEvent<HTMLInputElement>)=>void;placeholder?:string;type?:string;className?:string}) { return <input value={value} onChange={onChange} type={type} placeholder={placeholder} className={cn("h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-base outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100 sm:h-10 sm:text-sm",className)}/> }
export function Select({value,onChange,children,className}:{value?:string;onChange?:(e:React.ChangeEvent<HTMLSelectElement>)=>void;children:React.ReactNode;className?:string}) { return <select value={value} onChange={onChange} className={cn("h-11 rounded-lg border border-slate-200 bg-white px-3 text-base outline-none focus:border-blue-400 sm:h-10 sm:text-sm",className)}>{children}</select> }
export function Modal({open,title,children,onClose}:{open:boolean;title:string;children:React.ReactNode;onClose:()=>void}) { useEffect(()=>{if(!open||typeof window==="undefined")return;window.dispatchEvent(new CustomEvent("admin:edit-lock-changed"));return()=>{window.setTimeout(()=>window.dispatchEvent(new CustomEvent("admin:edit-lock-changed")),0)}},[open]); if(!open) return null; return <div data-admin-edit-lock="true" className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/35 p-2 sm:p-4" onMouseDown={onClose}><div className="max-h-[calc(100dvh-16px)] w-full max-w-2xl overflow-y-auto overscroll-contain rounded-xl border border-slate-200 bg-white shadow-2xl sm:max-h-[90vh] sm:rounded-2xl" onMouseDown={e=>e.stopPropagation()}><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white px-4 py-3 sm:px-5 sm:py-4"><h2 className="min-w-0 break-keep pr-3 font-bold">{title}</h2><button onClick={onClose} className="grid size-10 shrink-0 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 sm:size-8">✕</button></div><div className="p-4 sm:p-5">{children}</div></div></div> }
